version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  rabbitmq:
    build:
      context: ./Dockerfiles/rabbitmq/
    privileged: true
    user: root
    ports:
      - 8082:15672
      - 8083:5672
    container_name: rabbitmq
  ci-firewall:
    build:
      context: .
    
